version = 0.1

[default.deploy.parameters]
stack_name = "kopflab-micrologger"
region = "us-east-1"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
no_confirm_changeset = true
no_fail_on_empty_changeset = true